### ISSUE TITLE
US 011 [Restrict Ticker Choice]

### ISSUE THREAD

**Issue by misghna** [misghna/Fanus1#11]
A regular User with a "data Entry" privilege should be restricted only to the tickers assigned based on a general Config 

{
    "tickerAccess": {
        "type": "Restricted",
        "tickers": [
            "BABA",
            "FB"
        ]
    }
}
{
    "tickerAccess": {
        "type": "Any",
        "tickers": []
    }
}

**Comment by solinatx** [comment]
chief when u get a chance can you pls create an accnt for me with no ticker restriction to test the dynamic input field.
